### ISSUE TITLE
t

### ISSUE THREAD

**Issue by likuanppd** [lxiaorui/ElasticGNN#1]
Hi xiaorui,

What dose "10" mean in the dataset citeseer_meta_adj_0.05_10.npz? It's just order number?

**Comment by lxiaorui** [comment]
Hi oldppd,
 
The last number in the filename is the random seed used to generate the attack. However, in the provided code, the attacked graph is directly downloaded from DeepRobust through the code in code/dataset_adv.py: 

```
perturbed_data = DeepRobust_PrePtbDataset(root='/tmp/',
                    name=name,
                    attack_method='meta',
                    ptb_rate=ptb_rate)
```

Therefore, the provided data is not necessary. To avoid confusion, we would like to delete these datasets in this repository. Thanks for pointing this out.

Xiaorui

**Comment by likuanppd** [comment]
Thanks
